export default {
  TC_LOSS: 'TC_LOSS',
  TC_LOSS_GAIN: 'TC_LOSS_GAIN',
  LC_LOSS: 'LC_LOSS',
  BIO_LOSS: 'BIO_LOSS',
  INTACT_LOSS: 'INTACT_LOSS',
  FIRES: 'FIRES',
  LCC: 'LCC',
  SLOPE: 'SLOPE',
  ANALYSIS_GROUP_RESTORATION: 'ANALYSIS_GROUP_RESTORATION',
  ANALYSIS_GROUP_SLOPE: 'ANALYSIS_GROUP_SLOPE',
  ANALYSIS_GROUP_OTHER: 'ANALYSIS_GROUP_OTHER',
  ANALYSIS_TYPE_RESTORATION: 'ANALYSIS_TYPE_RESTORATION',
  ANALYSIS_TYPE_SLOPE: 'ANALYSIS_TYPE_SLOPE',
  GEOMETRY_POLYGON: 'polygon'
};
