export default {
  ACTIVE_FIRES: 'ACTIVE_FIRES',
  TREE_COVER: 'TREE_COVER',
  LAND_COVER: 'LAND_COVER',
  TREE_COVER_GAIN: 'TREE_COVER_GAIN',
  TREE_COVER_LOSS: 'TREE_COVER_LOSS',
  IFL: 'IFL',
  AG_BIOMASS: 'AG_BIOMASS',
  MASK: 'MASK',
  LEGEND_LAYER: 'LEGEND_LAYER',
  GROUP_LCD: 'GROUP_LCD',
  GROUP_LC: 'GROUP_LC',
  GROUP_WEBMAP: 'GROUP_WEBMAP',
  GROUP_BASEMAP: 'GROUP_BASEMAP'
};
