export default {
  ACTIVE_FIRES: 'ACTIVE_FIRES',
  TREE_COVER: 'TREE_COVER',
  LAND_COVER: 'LAND_COVER',
  GAIN: 'GAIN',
  LOSS: 'LOSS',
  GROUP_LCD: 'GROUP_LCD',
  GROUP_LC: 'GROUP_LC',
  GROUP_WEBMAP: 'GROUP_WEBMAP',
  GROUP_BASEMAP: 'GROUP_BASEMAP'
};
